DROP TABLE IF EXISTS data;
DROP TABLE IF EXISTS history;
DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS paths;
DROP TYPE IF EXISTS layer;

CREATE TYPE layer AS ENUM ('surface', 'middle', 'sea bed');

CREATE TABLE IF NOT EXISTS history (
  time TIMESTAMPTZ PRIMARY KEY,
  location JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS paths (
  uuid UUID PRIMARY KEY,
  name NAME NOT NULL,
  path JSON[] NOT NULL
);

CREATE TABLE IF NOT EXISTS trips (
  uuid UUID PRIMARY KEY,
  time TIMESTAMPTZ NOT NULL,
  path UUID NOT NULL REFERENCES paths
);

CREATE TABLE IF NOT EXISTS data (
  id SERIAL PRIMARY KEY,
  temperature FLOAT8 NOT NULL,
  location JSON NOT NULL,
  depth FLOAT8 NOT NULL,
  layer layer NOT NULL,
  time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  trip UUID NOT NULL REFERENCES trips
);
